[package]
name = "leifs/genrojotree"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
networker = "leifstout/networker@0.3.0"
observers = "sleitnick/observers@0.3.4"
promise = "quenty/promise@3.1.2"
trove = "sleitnick/trove@1.5.1"
dataservice = "carlito-code/dataservice@0.3.0"
shake = "sleitnick/shake@1.1.0"
zone = "zythdotdev/zone@1.1.0"
chance = "bestyear20/chance@1.0.4"
signal = "sleitnick/signal@2.0.3"
queue = "nightcycle/queue@2.3.3"
fusion = "elttob/fusion@0.3.0"
viewport = "bubshurb/viewportmodel@1.0.0"
satchel = "ryanlua/satchel@1.3.2"
robloxstatemachine = "prooheckcp/robloxstatemachine@1.1.7"
testez = "roblox/testez@0.4.1"